---
- hosts: centos
  become: yes
  #become_method: sudo
  tasks:
   - parted:
       device: /dev/nvme1n1
       number: 1
       flags: [ lvm ]
       state: present
   - filesystem:
       fstype: ext4
       dev: /dev/nvme1n1p1
   - mount:
       fstype: ext4
       src: /dev/nvme1n1p1
       path: /mnt/data
       state: mounted